
set nocompatible
set title
set encoding=utf-8
set backspace=indent,eol,start
set mouse=a
let mapleader=" "

source $HOME/.vim/vim-plug.vim


" vim: set ft=vim tw=80 expandtab tabstop=2 softtabstop=2 sw=2 :
