#!/usr/bin/env sh

# see this wiki page for information on script additions
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off 	        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  6              \
    bottom_padding               6              \
    left_padding                 6              \
    right_padding                6              \
    window_gap                   6              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add label="Reminders" app="^Reminders$" manage="off"
yabai -m rule --add label="Barrier" app="^Barrier$" manage="off"

yabai -m rule --add label="Loopback" app="^Loopback$" manage="off"
yabai -m rule --add label="Audio MIDI Setup" app="^Audio MIDI Setup$" manage="off" grid="4:4:1:1:2:2"

yabai -m rule --add label="Home" app="^Home$" manage="off"
yabai -m rule --add label="System Settings" app="^System Settings$" manage="off"
yabai -m rule --add label="Stickies" app="^Stickies$" manage="off"
yabai -m rule --add label="Calendar" app="^Calendar$" manage="off"

yabai -m rule --add label="Pixea" app="^Pixea$" manage="off"
yabai -m rule --add label="Iina" app="^IINA$" manage="off"

yabai -m rule --add label="WhatsApp" app="^WhatsApp$" manage="off" grid="4:4:1:1:2:2"
yabai -m rule --add label="FaceTime" app="^FaceTime$" manage="off"

yabai -m rule --add label="OBS Studio" app="^OBS Studio" manage="off" #grid="4:4:1:1:2:2"
yabai -m rule --add label="QuickTime" app="^QuickTime Player" manage="off"

yabai -m rule --add label="Finder Connect Dialog" title="Finder" app="^Connect to.*" manage="off"
yabai -m rule --add label="Music" app="Music" title="MiniPlayer" manage="off"

echo "yabai configuration loaded.."
