#/usr/bin/env zsh

if [[  -o interactive ]]; then
	# prepare environment for zshrc
	export ZPLUG_INSTALL="${HOME}/.local/share/zplug"
	export ZPLUG_HOME="${HOME}/.config/zplug"
fi

# export XDG_RUNTIME_DIR="/var/tmp/$EUID/" # not needed with systemd
