#/usr/bin/env zsh


if [[ ! -o interactive ]]; then
	#echo "ZSH login shell - limited environment"
	source ~/.zshrc.d/02-usr-local.zsh
fi

export HOMEBREW_NO_ENV_HINTS=1
export MallocNanoZone=0

export VCPKG_ROOT="$HOME/Developer/vcpkg"
export VCPKG_DISABLE_METRICS=1
