
source /usr/local/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
#antigen bundle git
#antigen bundle pip
antigen bundle osx
#antigen bundle command-not-found

#
## Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async

# Load the theme.
antigen bundle jackharrisonsherlock/common
antigen theme  jackharrisonsherlock/common

# Tell Antigen that you're done.
antigen apply

alias wtf='wtf -o'
eval "$(thefuck --alias)"
alias howmanyfucks="history | grep fuck | wc -l "

alias firepower='sudo /usr/libexec/ApplicationFirewall/socketfilterfw'
source $(brew --prefix)/etc/profile.d/z.sh

#oh-my-zsh seems to enable this by default. No me gusta en macOS.
DISABLE_AUTO_TITLE="true"


neofetch
