
source $ZPLUG_HOME/init.zsh

# Load the oh-my-zsh's library.
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Load oh-my-zsh plugins.
autoload colors && colors
setopt prompt_subst

#zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", defer:0
#zplug "plugins/git", from:oh-my-zsh
#zplug "plugins/macos", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
#zplug "plugins/pip", from:oh-my-zsh

zplug "plugins/command-not-found", from:oh-my-zsh

## Syntax highlighting bundle.
zplug "zsh-users/zsh-autosuggestions", defer:1
zplug "mafredri/zsh-async", defer:1
zplug "zsh-users/zsh-syntax-highlighting", defer:2

# Load the theme.

# Simple > theme
#zplug "jackharrisonsherlock/common", as:theme

# Robbyrussel + emoji
#zplug "meiokubo-zz/emoji.zsh-theme", as:theme

# Powerline theme
#zplug "caiogondim/bullet-train.zsh", as:theme

# Multi-line prompts
zplug "themes/gnzh", from:oh-my-zsh, as:theme
#zplug "halfo/lambda-mod-zsh-theme", as:theme
#zplug "zthxxx/jovial", as:theme
#zplug "yarisgutierrez/classyTouch_oh-my-zsh", as:theme

if ! zplug check --verbose; then
    #printf "Install? [y/N]: "
    #if read -q; then
    echo; zplug install
    #fi
fi

zplug load #--verbose
#  Zplug configuration is complete. User settings start below.

alias wtf='wtf -o'
eval "$(thefuck --alias)"
alias howmanyfucks="history | grep fuck | wc -l "

#oh-my-zsh seems to enable this by default. No me gusta en macOS.
DISABLE_AUTO_TITLE="true"

if [ -d ~/.zshrc.d ]; then
	for script in `ls ~/.zshrc.d/*.zsh`; do
		source ${script}
	done
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sdavid/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

test -e /home/sdavid/.iterm2_shell_integration.zsh && source /home/sdavid/.iterm2_shell_integration.zsh || true
